#!/usr/bin/python
#-*- coding: utf-8 -*-


# Plotter for Ace High Instruction files
# Copyright © 2008  Kristian Kjærgaard
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
#
# $Id$
#


# Principper: Programmet læser en ahi-fil og plotter den som vores
# plotter ville gøre det. Vi bruger programmet til at se, om
# konverteren virker og om plotteren faktisk plotter det, der står i
# instruktionsfilen.


print "Plotter for Ace High Instructions files"
print "$Id$"
