#!/usr/bin/python
#-*- coding: utf-8 -*-


# Converter from SVG files to Ace High Instruction files
# Copyright © 2008  Kristian Kjærgaard
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
#
# $Id
#

# Principper: Vi omsætter alle kurver til en række punkter, som vi
# tegner lige streger mellem.
#
# For dokumentation: se diagrammerne
#

import xml.parsers.expat


class Point:
    def __init__(self, _x, _y):
        self.x = _x
        self.y = _y


print "Jeg er et Python-program"
p = Point(5,3)
print p.x, p.y
